version: '3.4'

services: 

  frontend:
    image: pizzafrontend
    build:
      context: frontend
      dockerfile: Dockerfile
    environment: 
      - backendUrl=http://backend
    ports:
      - "5902:80"
    depends_on: 
      - backend
  backend:
    image: pizzabackend
    build: 
      context: backend
      dockerfile: Dockerfile
    environment: 
      - NEW_PIZZA_FROM_ENV="Hawai from Docker Compose"
      - SECRET_USERNAME="user"
      - SECRET_PASSWORD="password"
    ports: 
      - "5900:80"
    