---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizzabackend
  namespace: secrets-k8s
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pizzabackend
    spec:
      containers:
      - name: pizzabackend
        image: alnroldan/pizzabackend:1.0.0
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
        - name: NEW_PIZZA_FROM_ENV
          value: "Hawai from K8s Manifiest"
  selector:
    matchLabels:
      app: pizzabackend
---
apiVersion: v1
kind: Service
metadata:
  name: pizzabackend
  namespace: secrets-k8s
spec:  
  ports:
  - port: 80
  type: ClusterIP
  selector:
    app: pizzabackend
